import type { Metadata } from 'next'
import './globals.css'
import './colors.css'
import Providers from '@/components/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-default-bg text-default-text relative flex h-screen w-screen items-center justify-center overflow-x-hidden overflow-y-auto backdrop-blur-xl">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  )
}
