import type { Metadata } from 'next'
import './globals.css'
import './colors.css'
import Providers from '@/components/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-default-bg text-default-text flex h-screen w-screen items-center justify-center overflow-x-hidden overflow-y-auto backdrop-blur-xl">
          <div className="border-border-1 relative h-full max-h-[932px] w-[430px] border-x border-t border-solid bg-(image:--color-sidebar) backdrop-blur-sm">
            <Providers>{children}</Providers>
          </div>
        </div>
      </body>
    </html>
  )
}
